# Generated by Django 3.0.2 on 2020-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20201208_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Sobrestante', 'Sobrestante'), ('Pipas', 'Pipas'), ('Alcantarillado', 'Alcantarillado')], default=(('Administrador', 'Administrador'), ('Sobrestante', 'Sobrestante'), ('Pipas', 'Pipas'), ('Alcantarillado', 'Alcantarillado')), max_length=20, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='disponibilidad',
            field=models.TextField(choices=[('Disponible', 'Disponible'), ('En fuga', 'En fuga'), ('Fuera de servicio', 'Fuera de servicio')], default='Disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportesempleado',
            name='foto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reportesusuario',
            name='foto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reportesusuario',
            name='geolocalizacion',
            field=models.CharField(max_length=200, verbose_name='Geolocalización'),
        ),
    ]
