# Generated by Django 3.0.2 on 2021-01-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_auto_20210101_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportesusuario',
            name='foto',
            field=models.CharField(max_length=250),
        ),
    ]
