# Generated by Django 3.0.2 on 2020-11-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=10)),
                ('cargo', models.CharField(choices=[('Administrador', 'Administrador'), ('Sobrestante', 'Sobrestante')], max_length=20)),
                ('num_empleado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=45)),
                ('num_contrato', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
