# Generated by Django 3.0.2 on 2020-11-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Sobrestante', 'Sobrestante')], default=(('Administrador', 'Administrador'), ('Sobrestante', 'Sobrestante')), max_length=20),
        ),
    ]
