# Generated by Django 3.0.2 on 2020-12-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='num_empleado',
            field=models.CharField(max_length=45, unique=True, verbose_name='Número de empleado'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='num_contrato',
            field=models.CharField(max_length=45, unique=True, verbose_name='Número de contrato'),
        ),
    ]
