# Generated by Django 3.0.2 on 2020-12-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='disponibilidad',
            field=models.TextField(choices=[('Disponible', 'Disponible'), ('En fuga', 'En fuga')], default='Disponible', max_length=50),
        ),
    ]
