# Generated by Django 3.0.2 on 2020-11-24 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20201123_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportesUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
                ('foto', models.CharField(max_length=50)),
                ('prioridad', models.CharField(choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave')], default=(('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave')), max_length=20)),
                ('geoLocalizacion', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('cp', models.IntegerField(blank=True)),
                ('num_interior', models.IntegerField(blank=True)),
                ('num_exterior', models.IntegerField(blank=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Reportado', 'Reportado'), ('En reparación', 'En reparación'), ('Reparado', 'Reparado')], default=(('Reportado', 'Reportado'), ('En reparación', 'En reparación'), ('Reparado', 'Reparado')), max_length=20)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='ReportesEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=45)),
                ('foto', models.CharField(max_length=50)),
                ('prioridad', models.CharField(choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave')], default=(('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave')), max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Reportado', 'Reportado'), ('En reparación', 'En reparación'), ('Reparado', 'Reparado')], default=(('Reportado', 'Reportado'), ('En reparación', 'En reparación'), ('Reparado', 'Reparado')), max_length=20)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Empleados')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('id_reporte_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.ReportesEmpleado')),
            ],
        ),
    ]
