# Generated by Django 3.0.2 on 2020-11-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20201125_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportesusuario',
            name='tipo_anomalia',
            field=models.CharField(choices=[('Falta de agua', 'Falta de agua'), ('Falta de presion', 'Falta de presion'), ('Fuga en la red Hidraulica', 'Fuga en la red Hidraulica'), ('Fuga en la toma', 'Fuga en la toma'), ('Inspeccion', 'Inspeccion'), ('Material listo', 'Material listo'), ('Toma obstruida', 'Toma obstruida'), ('Toma desconectada', 'Toma desconectada'), ('Desazolve', 'Desazolve')], default=(('Falta de agua', 'Falta de agua'), ('Falta de presion', 'Falta de presion'), ('Fuga en la red Hidraulica', 'Fuga en la red Hidraulica'), ('Fuga en la toma', 'Fuga en la toma'), ('Inspeccion', 'Inspeccion'), ('Material listo', 'Material listo'), ('Toma obstruida', 'Toma obstruida'), ('Toma desconectada', 'Toma desconectada'), ('Desazolve', 'Desazolve')), max_length=50),
        ),
        migrations.AlterField(
            model_name='reportesusuario',
            name='tipo_servicio',
            field=models.CharField(choices=[('Agua potable', 'Agua potable'), ('Pipas', 'Pipas'), ('Alcantarillado', 'Alcantarillado')], default=(('Agua potable', 'Agua potable'), ('Pipas', 'Pipas'), ('Alcantarillado', 'Alcantarillado')), max_length=50),
        ),
        migrations.AlterField(
            model_name='reportesusuario',
            name='zona',
            field=models.CharField(choices=[('Nuevos desarrollos', 'Nuevos desarrollos'), ('Urbana', 'Urbana'), ('Conurbada', 'Conurbada')], default=(('Nuevos desarrollos', 'Nuevos desarrollos'), ('Urbana', 'Urbana'), ('Conurbada', 'Conurbada')), max_length=50),
        ),
    ]
