# Generated by Django 3.1.3 on 2020-12-05 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20201201_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportesusuario',
            old_name='geoLocalizacion',
            new_name='geolocalizacion',
        ),
        migrations.AlterField(
            model_name='reportesempleado',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.empleados', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='reportesempleado',
            name='id_repoteUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.reportesusuario', verbose_name='Folio seguimiento'),
        ),
        migrations.AlterField(
            model_name='reportesusuario',
            name='id_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.empleados', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='reportesusuario',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.usuarios', verbose_name='Usuario'),
        ),
    ]
