# Generated by Django 3.0.2 on 2020-11-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_auto_20201125_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='calle',
            field=models.CharField(blank=True, max_length=45, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='colonia',
            field=models.CharField(blank=True, max_length=45, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cp',
            field=models.IntegerField(blank=True, default=0, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apellidos',
            field=models.CharField(max_length=45, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(max_length=45, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=45, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='num_contrato',
            field=models.CharField(max_length=45, verbose_name='Número de contrato'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
    ]
