# Generated by Django 3.0.2 on 2020-11-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_auto_20201129_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='calle',
            field=models.CharField(blank=True, max_length=45, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='colonia',
            field=models.CharField(blank=True, max_length=45, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='cp',
            field=models.IntegerField(blank=True, default=0, verbose_name='Código Postal'),
        ),
    ]
